version: '3.8'
services:
  app:
    build: .
    container_name: backend_app
    environment:
      - DB_URL=jdbc:postgresql://db:5432/socialmediadb
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - jwt.secret=${JWT_SECRET}
      - jwt.audience=${JWT_AUDIENCE}
      - jwt.domain=${JWT_DOMAIN}
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: socialmediadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local